export const buildFallbackAnalysis = (incident: any) => {
  const sev = incident.severity
  const sevCopy: Record<string, string> = {
    LOW: 'Low',
    MEDIUM: 'Medium',
    HIGH: 'High',
    CRITICAL: 'Critical',
  }

  const summary = `A ${sevCopy[sev]} severity incident was detected involving ${incident.affectedEmail || incident.affectedUsername || 'a monitored asset'} at ${incident.organizationName || 'your organization'}. Exposed data includes ${(incident.exposedData || []).join(', ') || 'credentials'}.`

  const impact = `Sensitive data belonging to ${incident.affectedEmail || incident.affectedUsername || 'a monitored account'} was exposed in a ${sevCopy[sev]} leak. Unauthorized access could lead to account takeover, credential stuffing, and lateral movement within the organization.`

  const recommendations = []
  const exposedData = incident.exposedData || []
  const riskFactors = incident.riskFactors || []

  if (exposedData.includes('password') || riskFactors.some((f: string) => f.includes('Password'))) {
    recommendations.push('Force a password reset for the affected account immediately.')
  }
  if (riskFactors.some((f: string) => f.includes('Admin'))) {
    recommendations.push('Treat this as a privileged account compromise; review all admin sessions and enable MFA.')
  }
  recommendations.push('Enable multi-factor authentication on all monitored accounts.')
  recommendations.push('Monitor for unusual login activity and credential stuffing attempts.')
  recommendations.push('Review audit logs for the affected account for the last 30 days.')

  return {
    summary,
    impact,
    reasoning: 'Generated by the deterministic fallback engine based on risk factors and exposed data types.',
    recommendations,
    model: 'fallback-engine',
  }
}

export const analyzeIncident = async (incident: any) => {
  const apiKey = process.env.GEMINI_API_KEY
  const model = process.env.GEMINI_MODEL || 'gemini-1.5-pro'

  if (apiKey) {
    try {
      const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: 'You are a SOC analyst. Given this incident JSON, return ONLY valid JSON with keys: summary, impact, reasoning, recommendations (array of strings). No markdown. Incident: ' +
                    JSON.stringify({
                      severity: incident.severity,
                      riskScore: incident.riskScore,
                      affectedEmail: incident.affectedEmail,
                      affectedUsername: incident.affectedUsername,
                      exposedData: incident.exposedData,
                      riskFactors: incident.riskFactors,
                    }),
                },
              ],
            },
          ],
        })
      })

      if (!res.ok) throw new Error('Gemini API call failed')

      const data = await res.json()
      const text = data.candidates?.[0]?.content?.parts?.[0]?.text || ''
      const cleaned = text.replace(/```json|```/g, '').trim()
      const parsed = JSON.parse(cleaned)
      return { ...parsed, model: model }
    } catch (err) {
      console.warn('⚠️ Gemini call failed, using fallback engine:', err)
      return buildFallbackAnalysis(incident)
    }
  }
  return buildFallbackAnalysis(incident)
}
